### PR TITLE
[185740] Write log

### PR DESCRIPTION
**Pull request by aDaichiOta**
https://acsmine.tok.access-company.com/redmine/issues/185740

### CODE REVIEW

**Comment by aMasakiTakahashi** [comment]
LGTM!

**Comment by aYukiSekiguchi** [comment]
Please write more meaningful commit log when you'll merge this into master.
For example, `Write async job start and end log to AntikytheraCore.Logger`

**Comment by ttokit** [comment]
LGTM!

**Comment by irisTa56** [comment]
LGTM!

**Pull request merged**
