### PR TITLE
[241465] Don't parse JSON body if Content-Encoding is specified

### PR DESCRIPTION
**Pull request by aYukiSekiguchi**
https://acsmine.tok.access-company.com/redmine/issues/241465

### CODE REVIEW

**Review by irisTa56 — APPROVED** [review]
LGTM!

**Review by Fumipo-Theta — APPROVED** [review]
LGTM!

**Review by aMasakiTakahashi — APPROVED** [review]
LGTM!
(Please merge on or after 2/1.)

**Comment by aYukiSekiguchi** [comment]
> LGTM! (Please merge on or after 2/1.)

I agreed with Takahashi-san that I'll merge this on 28th to allow gear developers test this on the dev env.

**Pull request merged**
