### PR TITLE
[190996] upgrade some dependencies

### PR DESCRIPTION
**Pull request by irisTa56**
https://acsmine.tok.access-company.com/redmine/issues/190996

Updating tool libraries, raft_fleet and gettext.

### CODE REVIEW

**Comment by aMasakiTakahashi** [comment]
Can you upgrade `raft_fleet` too?
(Upgrading it in another PR is also OK.)

**Comment by irisTa56** [comment]
> Can you upgrade `raft_fleet` too?

Sure.
Actually, I planed to upgrade it in another PR, but it's easier to upgrade it in this PR.
I also upgrade patch-version of gettext.

**Comment by aMasakiTakahashi** [comment]
>Sure.
>Actually, I planed to upgrade it in another PR, but it's easier to upgrade it in this PR.
>I also upgrade patch-version of gettext.

Thank you!
LGTM

**Comment by ttokit** [comment]
LGTM

**Comment by aDaichiOta** [comment]
LGTM!

**Pull request merged**
