### PR TITLE
150737 Upgrade elixir to v1.7.4

### PR DESCRIPTION
**Pull request by toyoaki-k**
https://acsmine.tok.access-company.com/redmine/issues/150737

In ```.credo.exs``` I removed ```Credo.Check.Readability.PreferUnquotedAtoms``` and ```Credo.Check.Warning.LazyLogging``` because these checks are incompatible with elixir(1.7.0>=).
* https://github.com/rrrene/credo/blob/26afbaad9590db41b46d20252809db9a1d1590a4/CHANGELOG.md#0100
* https://github.com/rrrene/credo/blob/26afbaad9590db41b46d20252809db9a1d1590a4/CHANGELOG.md#103

### CODE REVIEW

**Comment by skirino** [comment]
Travis tests are failing due to the incompatible version of `ex_doc`.
Let's upgrade it to the latest working version.

**Comment by skirino** [comment]
> Travis tests are failing due to the incompatible version of `ex_doc`.

No, my bad.
Although we still have to update `ex_doc`, it's not the direct cause of the travis test failures.
Let's first complete this PR (merge into master).
As you wrote in the ticket, we then need to manually update the `antikythera` version in `antikythera_instance_example` to fix the failing tests.

**Comment by toyoaki-k** [comment]
Roger Dodger!

**Comment by skirino** [comment]
In https://github.com/access-company/antikythera/pull/42#issuecomment-480831750 I meant "complete this PR by updating `ex_doc`".
Anyway, move on and update `ex_doc` (directly push to the master branch).

**Comment by toyoaki-k** [comment]
Roger!

**Pull request merged**
