### PR TITLE
[218823] Update recon

### PR DESCRIPTION
**Pull request by aDaichiOta**
https://acsmine.tok.access-company.com/redmine/issues/218823#note-16

### CODE REVIEW

**Comment by aYukiSekiguchi** [comment]
I don't think our `mix test` covers `:recon` usage.
Could you test the following function call, which antikythera uses, on your local machine?
```ex
:recon.proc_count(:reductions, 20_000)
:recon.proc_count(:message_queue_len, 5)
```

**Review by aYukiSekiguchi — APPROVED** [review]
LGTM if `:recon` tests are passed.

**Comment by aDaichiOta** [comment]
> I don't think our mix test covers :recon usage.
> Could you test the following function call, which antikythera uses, on your local machine?
> ```elixir
> :recon.proc_count(:reductions, 20_000)
> :recon.proc_count(:message_queue_len, 5)
> ```

Thanks for your review.
Now I called these functions by hand and confirmed that the format did not change.
And these functions are used in `AntikytheraCore.PeriodicLog.{ReductionBuilder,MessageBuilder}`. I also confirmed that the test fails by changing `:reductions` to `:reductions_`.

**Comment by aYukiSekiguchi** [comment]
Thank you for the test!

**Review by aMasakiTakahashi — APPROVED** [review]
LGTM!

**Pull request merged**
