### PR TITLE
[185700] Get elixir version from antikythera's `.tool-versions` in CircleCI workflow

### PR DESCRIPTION
**Pull request by irisTa56**
https://acsmine.tok.access-company.com/redmine/issues/185700

Get elixir version from [this file](https://github.com/access-company/antikythera_instance_example/blob/master/.tool-versions) rather than update manually.

### CODE REVIEW

**Comment by aMasakiTakahashi** [comment]
LGTM!

**Comment by ttokit** [comment]
LGTM!

**Comment by aDaichiOta** [comment]
LGTM ！！！

**Comment by ttokit** [comment]
LGTM again!

**Comment by aMasakiTakahashi** [comment]
LGTM!

**Pull request merged**
