### PR TITLE
[177185] Remove zip lib

### PR DESCRIPTION
**Pull request by aNobuhisaMasaki**
https://acsmine.tok.access-company.com/redmine/issues/177185

Just removed ZIP library, because it is immature as a common component which can be executed nicely and safely for now.

### CODE REVIEW

**Comment by ttokit** [comment]
LGTM.

**Comment by aNobuhisaMasaki** [comment]
@ttokit Thank you for the review!
@aMasakiTakahashi This is a simple removal, but could you confirm?

**Comment by aMasakiTakahashi** [comment]
[This line](https://github.com/access-company/antikythera/blob/5637618356382334de8da689ef0ed56cf0b51846/.circleci/config.yml#L17) is needed?

**Comment by aNobuhisaMasaki** [comment]
@aMasakiTakahashi 

> [This line](https://github.com/access-company/antikythera/blob/5637618356382334de8da689ef0ed56cf0b51846/.circleci/config.yml#L17) is needed?

No, this call of `apt-get` is validated only in testing environment.

**Comment by aNobuhisaMasaki** [comment]
@aMasakiTakahashi 

>> [This line](https://github.com/access-company/antikythera/blob/5637618356382334de8da689ef0ed56cf0b51846/.circleci/config.yml#L17) is needed?

> No, this call of `apt-get` is validated only in testing environment.

Removed in 9646813 .

**Comment by aMasakiTakahashi** [comment]
LGTM. Thanks.
Can I merge this?
(Do you still use `Zip.zip` ?)

**Comment by aNobuhisaMasaki** [comment]
@aMasakiTakahashi Thank you for the review!

> Can I merge this?
> (Do you still use Zip.zip ?)

Yes, please.
`Zip.zip` is not referenced any more.

**Pull request merged**
